Feature/michael/add events
PythonFreeCourse/calendar pull request #101
Opened 2021-01-20 20:55 UTC by Michael-B-D

after correcting some notes

2021-01-22 05:46 UTC, yammesicka requested changes

2021-01-22 05:46 UTC, yammesicka commented on .vscode/settings.json
> +{
Be sure this file is in the `.gitignore`.
Remove it using `git rm` if needed.

2021-01-22 05:46 UTC, yammesicka commented on app/database/config.py
> +db_url = "sqlite:///./calendar_app.db"
Please use `config.py.example`

2021-01-22 05:46 UTC, yammesicka commented on app/database/database.py
> +from .config import db_url
Please import it as an absolute import

2021-01-22 05:46 UTC, yammesicka commented on app/database/models.py
> +    # repeated_event_id = Column(Integer, ForeignKey("repeated_events.id"))
Please remove commented out code

2021-01-22 05:46 UTC, yammesicka commented on app/main.py
> +def get_db():
Already exists in another file :)

2021-01-22 05:46 UTC, yammesicka commented on app/main.py
> +@app.get("/profile/{user_id}/EditEvent", response_class=HTMLResponse)
Prefer adding this endpoint on the relevant file on app/routers. The `main.py` file should be clean.

2021-01-22 05:46 UTC, yammesicka commented on app/templates/profile.html
>                  <div class="card card-profile mb-3">
Why have you removed this line?

2021-01-22 05:46 UTC, yammesicka commented on app/templates/profile.html
>              <div class="col-3">
Please remove the database file

2021-01-22 05:46 UTC, yammesicka commented on tests/test_app.py
> +    assert response.status_code == 200
Prefer `.ok`

2021-01-22 05:46 UTC, yammesicka commented on tests/test_app.py
> +event_test_data = [(
Can you please add this event as a fixture?

2021-01-23 18:06 UTC, ivarshav commented on app/main.py
> +def add_event(values: dict, db) -> Event:
Move to `internal/event` ?

2021-01-24 19:07 UTC, ivarshav commented on app/main.py
> +# app.mount("static", StaticFiles(directory="static"), name="static")
Remove this line? :)

2021-01-25 18:14 UTC, yammesicka commented
Can you please send this PR to `:develop` and not to `:main`? :)

2021-01-25 22:36 UTC, closed without merging

2021-01-25 22:37 UTC, Michael-B-D commented
make a new PR after sync with the ripo updates