WIP Speedy Meetings
PythonFreeCourse/calendar pull request #125
Opened 2021-01-23 23:09 UTC by omrizhaki

* Created a setting in the DB that will record whether a user has Speedy Meetings enabled
* Added an option to use default_end time, in case you don't want the user to decide when the meeting will end
* Added a function that will shorten the default meeting time in case Speedy Meetings is enabled

2021-01-24 05:01 UTC, yammesicka requested changes

2021-01-24 05:01 UTC, yammesicka commented on app/database/models.py
> +    default_end = get_default_end_time()
This class is part of the ORM, it must be of type `Column` or a `relationship`.

You can check the SQLAlchemy docs to see how to add default value to the `end` column.

2021-01-25 15:53 UTC, ivarshav commented on app/database/models.py
> +    def get_user_by_id(self, owner_id):
Is it needed? can't we just call user.owner?

2021-01-25 15:53 UTC, ivarshav commented on app/database/models.py
> +            return default_duration * .75
what is 0.75?

2021-01-25 15:54 UTC, ivarshav commented on app/database/models.py
> +    def get_default_duration(self):
Why it's part of the table model?

2021-01-30 19:10 UTC, closed without merging