Profile update menu
PythonFreeCourse/calendar pull request #71
Opened 2021-01-17 18:41 UTC by leddest

Now a user able to:
- Change full name
- Change email
- Change short user description ("about me")
- Update profile picture

2021-01-17 19:44 UTC, ivarshav commented on app/database/models.py
> +    description = Column(String, default="Happy new user!")
Maybe set the defauls in a const ?

2021-01-17 19:50 UTC, ivarshav commented on app/routers/profile.py
> +    user = session.query(User).filter_by(id=1).first()
Probably should add a TODO to replace the `id=1` part

2021-01-17 19:50 UTC, efratush commented on app/routers/profile.py
> +    user = session.query(User).filter_by(id=1).first()
Filter always id=1 not by user id?

2021-01-17 19:51 UTC, ivarshav commented on schema.md
> +    └── config.py
conftest

2021-01-17 19:52 UTC, ivarshav commented on tests/test_profile.py
> +    assert profile.status_code == 302
Can use `from starlette import status`

2021-01-17 19:57 UTC, leddest commented on schema.md
> +    └── config.py
Thank you for paying attention

2021-01-17 20:02 UTC, leddest commented on app/routers/profile.py
> +    user = session.query(User).filter_by(id=1).first()
There's still no user verification

2021-01-18 16:50 UTC, yammesicka requested changes

2021-01-18 16:50 UTC, yammesicka commented on app/routers/profile.py
> +def get_new_user():
Please change to "get_placeholder_user"

2021-01-18 16:50 UTC, yammesicka commented on app/templates/base.html
> +    <script>
Can you please move it to another JS file?

2021-01-18 16:50 UTC, yammesicka commented on app/routers/profile.py
> +    img = Image.open(io.BytesIO(image))
Can we somehow close this handler?

2021-01-18 16:50 UTC, yammesicka commented on app/routers/profile.py
> +    response = RedirectResponse(url=url, status_code=HTTP_302_FOUND)
You can directly return it

2021-01-18 16:50 UTC, yammesicka commented on app/routers/profile.py
> +        print(user.avatar)
Remove the print

2021-01-18 23:26 UTC, closed without merging